urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),
    path('post/<int:pk>/', views.DetailView.as_view(), name='detail'),
    #path('post/new/', views.PostFormView().as_view(), name='new_post'),
    path('drafts/', views.DraftView.as_view(), name='draft_list'),
    path('post/<int:pk>/publish/', views.publish, name='publish'),
    path('post/<int:pk>/remove/', views.remove, name='remove'),
    path('post/<int:pk>/edit/', views.edit, name='edit'),
]

models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation

class Post(models.Model, HitCountMixin):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to = "images/")
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
	post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	comment = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)

	def approve(self):
		self.approved_comment = True
		self.save()

forms.py
from django import forms

from .models import *

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text', 'image',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('comment',)

views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from .forms import *
from core.models import *
from core.forms import *
from django.views import generic
from django.utils import timezone
from django.urls import reverse
from hitcount.views import HitCountDetailView

class BlogView(generic.ListView):
    template_name = 'blog/blog.html'
    paginate_by = 5
    
    def get_context_data(self, **kwargs):
        context = super(BlogView, self).get_context_data(**kwargs)
        context.update({
            'top_hits': Post.objects.filter(published_date__lte=timezone.now()).order_by("-hit_count_generic__hits")[:10],
        })
        return context

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class DetailView(HitCountDetailView):
    model = Post
    count_hit = True
    template_name = 'blog/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        comments = Comment.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')
        form = CommentForm()
        context.update({
            'form': form,
            'comments': comments,
        })
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.get_object()
            comment.author = request.user
            comment.save()
        return HttpResponseRedirect(reverse('blog:detail', args=(comment.post.id,)))

class DraftView(generic.ListView):
    template_name = 'blog/draft_list.html'
    context_object_name = 'post_list'
    paginate_by = 5
    
    def get_context_data(self, *args, **kwargs):
        context = super(DraftView, self).get_context_data(**kwargs)
        contacts = Contact.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')
        top_hits = Post.objects.filter(published_date__lte=timezone.now()).order_by("-hit_count_generic__hits")[:10]
        form = PostForm()
        context.update({
            'form': form,
            'contacts': contacts,
            'top_hits': top_hits
        })
        return context

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-created_date')

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
        return HttpResponseRedirect(reverse('core:index'))

@login_required
def publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))

@login_required
def remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return HttpResponseRedirect(reverse('core:index'))

@login_required
def edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form = PostForm(request.POST, request.FILES, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
		return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/form.html', {'form': form})

templates/blog/blog.html
{% extends 'core/no_carousel.html' %}
{% load hitcount_tags %}

    {% block content %}
        <div class="row">
            <div class="col-70 left">
                <h1>Recently posted</h1></br>
                {% for post in page_obj %}
                <div class="post-list-item">
                    <img class="blog-img" src="{{ post.image.url }}"/>
                    <div class="post-content">
                        <h3>{{ post.title }}</h3>
                        <small>
                            {{ post.published_date|date:'d F, Y' }} |
                            By {{ post.author }} |
                            Reads: {% get_hit_count for post %}
                        </small>
                        <br/><br/>
                        <p>{{ post.text|truncatechars:200 }}</p>
                        <a href="{% url 'blog:detail' post.id %}" class="link-button">Read more</a>
                        <a href="{% url 'blog:detail' post.id %}#comments" class="link-button">Comment</a>
                    </div>
                </div>
                {% empty %}
                <p>No posts are available.</p>
                {% endfor %}

                {% if page_obj.has_other_pages %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                    <li class="page-item disabled"><a>&laquo;</a></li>
                    {% endif %}
                    {% for x in page_obj.paginator.page_range %}
                        {% if x == page_obj.number %}
                    <li class="page-item active"><a>{{ x }}</a></li>
                        {% else %}
                    <li class="page-item"><a href="?page={{ x }}">{{ x }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                    <li class="page-item disabled"><a>&raquo;</a></li>
                    {% endif %}
                </ul>
            {% endif %}
            </div>
            <div class="col-30 right">
                <form action="{% url 'query:query_results' %}">
                    <input type="text" placeholder="Search..." name="q">
                    <button type="submit">Search</button>
                </form>
                </br>
                <h4>Top posts</h4>
                {% for post in top_hits %}
                <p><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></p>
                {% endfor %}
            </div>
        </div>
    {% endblock %}

templates/blog/detail.html
{% extends 'core/no_carousel.html' %}
{% load hitcount_tags %}

    {% block content %}
        <div class="post-list-item">
            <img class="blog-img" src="{{ post.image.url }}"/>
            <div class="post-content">
                <h1>{{ post.title }}</h1>
                {% if post.published_date %}
                <p>                
                <small>
                    {{ post.published_date|date:'d F, Y' }} |
                    By {{ post.author }} |
                    Reads: {% get_hit_count for post %}
                </small></p>
                {% else %}
                    {% if user.is_superuser %}
                <a class="link-button" href="{% url 'blog:publish' post.id %}">Publish</a>
                    {% endif %}
                {% endif %}
                {% if user.is_superuser %}
                <a class="link-button" href="{% url 'blog:edit' post.id %}">Edit</a>
                <a class="link-button" href="{% url 'blog:remove' post.id %}">Delete</a>
                {% endif %}
                <p>{{ post.text }}</p>
            </div>
        </div>
        <div id="comments">
            <h3>Comments</h3>
            {% if user.is_authenticated %}
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit">
            </form>
            {% else %}
            <p>Please log in or sign up to comment</p>
            {% endif %}
            {% for comment in comments %}
            <div class="comment">
                <a href="{% url 'user_profile:profile_view' pk=comment.author.pk %}">
                    <img class="comment-user" src='/media/{{ comment.author.profile.profile_picture }}'/>
                </a>
                <small>
                    <bold>{{ comment.author }}</bold> | 
                    {{ comment.created_date }}
                </small>
                <p>{{ comment.comment }}</p>
            </div>
            {% empty %}
            <p>There are no comments</p>
            {% endfor %}
        </div>
    {% endblock %}

templates/blog/draft_list.html
{% extends 'core/no_carousel.html' %}
{% load bootstrap4 %}

    {% block content %}
        {% if user.is_superuser %}
        <div class="row">
            <div class="col-70 left">
                <form role="form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Post" class="btn btn-secondary">
                </form>
            </div>
            <div class="col-30 right">
                <h3>Drafts</h3>
                {% for post in post_list %}
                <div class="admin-item">
                    <h3>{{ post.title }}</h3>
                    <p>{{ post.text }}</p>
                    <a href="{% url 'blog:detail' post.id %}" class="more-button">Read more</a>
                </div>
                {% empty %}
                <p>No drafts are available.</p>
                {% endfor %}

                {% if page_obj.has_other_pages %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                    <li class="page-item disabled"><a>&laquo;</a></li>
                    {% endif %}
                    {% for x in page_obj.paginator.page_range %}
                        {% if x == page_obj.number %}
                    <li class="page-item active"><a>{{ x }}</a></li>
                        {% else %}
                    <li class="page-item"><a href="?page={{ x }}">{{ x }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                    <li class="page-item disabled"><a>&raquo;</a></li>
                    {% endif %}
                </ul>
                {% endif %}
                <h3>Contacts</h3>
                {% for post in contacts %}
                <div class="admin-item">
                    {{ post.email }}
                    <p>{{ post.message }}</p>
                </div>
                {% empty %}
                <p>No drafts are available.</p>
                {% endfor %}
            </div>
        </div>
        {% else %}
        <p>You are not authorized to view this page</p>
        {% endif %}
    {% endblock %}

templates/blog/form.html
{% extends 'core/no_carousel.html' %}
{% load bootstrap4 %}

    {% block content %}
        {% if user.is_superuser %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form role="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form layout=layout %}
            <input type="submit" value="Post" class="btn btn-secondary">
        </form>
        {% else %}
        <p>You are not authorized to view this page</p>
        {% endif %}
    {% endblock %}